accounts/urls.py
from django.urls import re_path
from .import views

app_name = 'accounts'

urlpatterns = [
	re_path(r'^signup/$', views.signup_view, name="signup"),
	re_path(r'^login/$', views.login_view, name="login"),
	re_path(r'^logout/$', views.logout_view, name="logout"),
]

miner/urls.py
from django.urls import re_path
from . import views
# from rest_framework.urlpatterns import format_suffix_patterns

app_name = 'miner'

urlpatterns = [
    re_path(r'^$', views.index, name = 'index'),
    re_path(r'^apipool', views.miner_pool.as_view(), name='api_pool'),
    re_path(r'^(?P<miner_id>[0-9]+)/$', views.detail, name = 'detail'),
    re_path(r'^create/$', views.miner_create, name="create"),
    re_path(r'^change', views.change_pool, name='change'),
]

poolweb/urls.py
from django.contrib import admin
from django.urls import path, include, re_path


urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^miner/' , include('miner.urls')),
    re_path(r'^accounts/' , include('accounts.urls')),
]

accounts/models.py
from django.db import models

# Create your models here.

miner/models.py
from django.db import models
from django.contrib.auth.models import User
from rest_framework import serializers

class Pool(models.Model):
	name = models.CharField(max_length=200)
	para1 = models.CharField(max_length=200)
	para2 = models.CharField(max_length=200)
	para3 = models.CharField(max_length=200)
	para4 = models.CharField(max_length=200)
	para5 = models.CharField(max_length=200)
	para6 = models.CharField(max_length=200)

	def __str__(self):
		return self.name

class Miner(models.Model):
	name = models.CharField(max_length=100)
	para1 = models.IntegerField(default=0)
	owner = models.ForeignKey(User,on_delete=models.CASCADE,default=None)
	pool = models.ManyToManyField(Pool, through = 'PoolMux')

	def __str__(self):
		return self.name

class PoolMux(models.Model):
	miner = models.ForeignKey(Miner,on_delete=models.CASCADE,default=None)
	pool =  models.ForeignKey(Pool,on_delete=models.CASCADE,default=None)

# class PoolSerializer(serializers.ModelSerializer):

#     class Meta:
#         model = Pool
#         fields = ('name', 'para1','para2')

class MinerSerializer(serializers.ModelSerializer):

    class Meta:
        model = Miner
        fields = '__all__'

miner/forms.py
from django import forms
from . import models

class CreateMiner(forms.ModelForm):
	class Meta:
		model = models.Miner
		fields = ['name','para1']

class CreatePoolMux(forms.ModelForm):
	class Meta:
		model = models.PoolMux
		fields = ['pool', 'miner']

accounts/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
# Create your views here.

def signup_view(request):
	if request.method == 'POST':
		form = UserCreationForm(request.POST)
		if form.is_valid():
			user = form.save()
			login(request, user)
			return redirect('miner:index')
	else:	
		form = UserCreationForm()
	return render(request, 'accounts/signup.html', {'form' : form})

def login_view(request):
	if request.method == 'POST':
		form = AuthenticationForm(data=request.POST)
		if form.is_valid():
			user = form.get_user()
			login(request, user)
			return redirect('miner:index')
	else:
		form = AuthenticationForm()
	return render(request, 'accounts/login.html', {'form' : form})

def logout_view(request):
	if request.method == 'POST':
		logout(request)
		return redirect('accounts:login')

miner/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
# from .models import Miner
from .models import Miner, Pool, PoolMux, MinerSerializer
from django.contrib.auth.decorators import login_required
from . import forms

from django.core import serializers
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.renderers import JSONRenderer

# Create your views here.

@login_required(login_url="/accounts/login")
def index(request):
	miners = Miner.objects.filter(owner_id=request.user.id)
	context = {
		'miners': miners,
		'user': request.user,
	}
	# return HttpResponse("test index")
	return render(request, 'miner/index.html', context)

class miner_pool(APIView):

	def get(self, request):
		# miners = Miner.objects.filter(owner_id=request.GET.get('user', ''))
		# miners = serializers.serialize("json",Miner.objects.all())
		#
		queryset = Miner.objects.filter(owner_id=request.GET.get('user', ''))
		serializer = MinerSerializer(queryset, many=True)
		json = JSONRenderer().render(serializer.data)

		# return Response(miners, status=200)
		return HttpResponse(json, status=200)

@login_required(login_url="/accounts/login")
def detail(request, miner_id):
	machine = Miner.objects.get(pk=miner_id)
	pools = Pool.objects.all()
	try:
		pool_mux_id = PoolMux.objects.get(miner=miner_id).pool_id
	except:
		context = {'machine' : machine, 'pools': pools }
	else:
		now_pool = Pool.objects.get(pk=pool_mux_id)
		context = {'machine' : machine, 'pools': pools, 'now_pool': now_pool }
	return render(request, 'miner/miner_detail.html', context)

@login_required(login_url="/accounts/login")
def miner_create(request):
	if request.method == 'POST':
		form = forms.CreateMiner(request.POST)
		if form.is_valid():
			#save article to db
			instance = form.save(commit=False)
			instance.owner = request.user
			instance.save()
			return redirect('miner:index')
	else:
		form = forms.CreateMiner()
	return render(request, 'miner/miner_create.html', {'form' : form})

@login_required(login_url="/accounts/login")
def change_pool(request):
	if request.method == 'POST':
		form = forms.CreatePoolMux(request.POST)
		if form.is_valid():
			print('看這裡:', request.POST['pool'])
			try:
				miner = PoolMux.objects.get(miner=request.POST['miner'])
			except:
			  print("no miner")
			  form.save()
			else:
				update_object = PoolMux.objects.filter(miner=request.POST['miner'])
				update_object.update(pool=request.POST['pool'])
				update_miner = Miner.objects.filter(id=request.POST['miner'])
				update_miner.update(para1=request.POST['para1'])
		else:
			print('form不對')

	return redirect('miner:index')

accounts/templates/accounts/login.html
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>Miner</title>
</head>
<body>
	<h1>login</h1>
	<form class="#" action="{% url 'accounts:login' %}" method="post">
		{% csrf_token %}
		{{form}}
		<input type="submit" value="Login">
	</form>
</body>
</html>

accounts/templates/accounts/signup.html
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>Miner</title>
</head>
<body>
	<h1>signup</h1>
	<form class="#" action="/accounts/signup/" method="post">
		{% csrf_token %}
		{{form}}
		<input type="submit" value="Signup">
	</form>
</body>
</html>

miner/templates/miner/index.html
<!doctype html>
<html>
	<head>
	    <meta charset="utf-8">
	    <title>Miner</title>
	</head>
	<body>	
		<ul>
			<li>
				<form class="#" action="{% url 'accounts:logout' %}" method="post">
					{% csrf_token %}
					<button type="submit">Logout</button>
				</form>
			</li>
			<li>
				<a href="{% url 'miner:create' %}">Create</a>
			</li>
		</ul>
		<div class="articles">
			<h1>Your Id is : {{user.id}}</h1>
		    {% for miner in miners %}
		    	<h2><a href="{% url 'miner:detail' miner.id %}">{{ miner.name }}</a></h2>
		        <p>{{ miner.name }}</p>
		        <p>your pool id is : {{ miner.pool.all.first.id }}</p>
		    {% endfor %}
		</div>
	</body>
</html>

miner/templates/miner/miner_create.html
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>Miner</title>
</head>
<body>
	<div class="#">
		<h2>create a miner</h2>
		<form class="#" action="{% url 'miner:create' %}" method="post">
			{% csrf_token %}
			{{form}}
			<input type="submit" value="Create">
		</form>
	</div>
</body>
</html>

miner/templates/miner/miner_detail.html
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>Detail</title>
</head>
<body>
		<h1>{{ machine.name }}</h1>
		<h2>Period now : {{ machine.para1 }}</h2>
		<form action="{% url 'miner:change' %}" method="POST" >
			Period new: <input type="text" name="para1"><br>
			<input type="hidden" name="miner" value="{{machine.id}}">
			{% csrf_token %}
			<label>
				<tr>
					<td>choice</td>
					<td>
						<select name="pool">
							<option value="{{ now_pool.id }}">{{ now_pool.name }}</option>
							{% for pool in pools %}
								<option value="{{ pool.id }}">{{ pool.name }}</option>
							{% endfor %}
						</select>
					</td>
					<td><input type="submit" value="Submit" /></td>
				</tr>
			</label>
		</form>
</body>
</html>